name: Test

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  plugin-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

    - name: Install asdf tools
      uses: egose/actions/asdf-tools@9a09f2377dc8c8b8f8cfacc5f695448999670434

    - name: Move database-tools plugin to asdf plugins dir
      run: |
        mkdir -p ${ASDF_DIR}/plugins
        cp -r . ${ASDF_DIR}/plugins/database-tools

    - name: Run database-tools plugin tests
      run: |
        echo "Trying to list all versions of database-tools"
        asdf list all database-tools
        echo "Trying to install database-tools 0.12.3"
        asdf install database-tools 0.12.3
        asdf list database-tools | grep 0.12.3

    - uses: asdf-vm/actions/plugin-test@v4.0.1
      with:
        command: mongo-archive --version
