name: Test

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    paths-ignore:
    - '**.md'

jobs:
  plugin-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

    - name: Install asdf tools
      uses: egose/actions/asdf-tools@311fba04b7412f06d1cc7d77a5126a11e7c609e7

    - uses: asdf-vm/actions/plugin-test@v4
      with:
        command: mongo-archive --version
        version: 0.12.3
